version: '3.7'
services:
    # The ERP Container
    # -----------------
    # Accessing container via ssh: docker exec -u erp -it erp bash
    #
    erp:
      #image: sdp.registry.abas.sh/abas/test:2017r4n16p22
      image: sdp.registry.abas.sh/abas/test:2019r4n13
      init: true
      container_name: "erp"

      ports:
      - "${SSH_TEST_PORT:-2205}:22"
      - "${MINI_GUI_PORT:-8001}:80"
      - "${EDP_TEST_PORT:-6560}:6550"
      - "${GUI_TEST_PORT:-48592}:48392"

      environment:
      - ABAS_HOST=${ABAS_HOST}
      - ABAS_GUI_PORT=${GUI_TEST_PORT:-48592}

      # The hostname is very important, especially if you intend to use `docker commit`
      user: s3
      hostname: dockerbau
      command: ["sh", "-c", "cd /abas/erp && eval $$(sh denv.sh) && datmeta -s && /abas/bin/starteVersion.sh run" ]

    # nexus for publishing abas Essentials libraries
    nexus:
      image: sonatype/nexus:oss
      container_name: "nexus"
      ports:
      - "8081:8081"
